include: ["_pages"]
exclude: ["_includes/notes_graph.json"]
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).

# Settings
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://fleetingnotes.app" # the base hostname & protocol for your site, e.g. http://example.com
title: Fleeting Notes | Notes that extend your mind
tagline: Create notes that extend your brain
description:  Fleeting Notes helps you create notes that functions in a similar vein to the brain—through the connection of ideas.
logo: /assets/favicon.png
heading: Fleeting Notes # Change this
author:
  name: Matthew Wong
  url: https://thinkwong.com

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/notes/*.md"
    values:
      layout: "note"
      permalink: /notes/:title
  - scope:
      path: "_notes/posts/*.md"
    values:
      layout: "note"
      permalink: /posts/:title
